apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: vap
spec:
  stripPrefix:
    forceSlash: true
    prefixes:
      - /vap
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumina-ingress
  namespace: vap
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: vap-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /vap
        pathType: Prefix
        backend:
          service:
            name: lumina-service
            port:
              number: 80
