apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: gap
spec:
  stripPrefix:
    forceSlash: true
    prefixes:
      - /gap
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumina-ingress
  namespace: gap
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: gap-strip-prefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /gap
            pathType: Prefix
            backend:
              service:
                name: lumina-service
                port:
                  number: 80
